/**
 * Drop-in Ionicons → Lucide replacement.
 * Use exactly like <Icon name="..." size={x} color={y} />
 */
import React from 'react';
import {
  Archive, ArrowLeft, AtSign,
  Ban, Bell, BellOff, Bookmark, Briefcase, Calendar, Camera, Check,
  CheckCheck, CircleCheck, ChevronDown, ChevronLeft, ChevronRight,
  ChevronUp, Circle, Clipboard, Clock, Copy, Download, Ellipsis,
  EllipsisVertical, ExternalLink, Eye, EyeOff, File, FileText,
  Globe, Heart, House, Image, Info, Key, Lock, LockKeyhole, LogOut,
  MapPin, Megaphone, Mic, MicOff, Music, Navigation, Paperclip,
  Pause, Pen, Phone, Play, Plus, CirclePlus, CircleMinus, RefreshCw,
  Reply, RotateCcw, ScanFace, Search, Send, Settings, Share2, Shield,
  SkipForward, Smile, Frown, Square, Star, Trash2, LockOpen, User, Users,
  Video, Volume2, X, Zap, MessageCircle,
  Headphones, ThumbsUp, Radio, CircleAlert, TriangleAlert, CircleX,
  SquareCheck, CloudUpload, CornerUpLeft, Flag, Laugh, Pencil,
  Grid, Tag, Hash, SquarePen,
} from 'lucide-react-native';
import type { LucideProps } from 'lucide-react-native';

const MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Navigation / arrows
  'arrow-back': ArrowLeft,
  'arrow-back-outline': ArrowLeft,
  'chevron-back': ChevronLeft,
  'chevron-back-outline': ChevronLeft,
  'chevron-forward': ChevronRight,
  'chevron-forward-outline': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-down-outline': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-up-outline': ChevronUp,

  // Chat / messaging
  'chatbubble': MessageCircle,
  'chatbubble-outline': MessageCircle,
  'chatbubbles': MessageCircle,
  'chatbubbles-outline': MessageCircle,
  'send': Send,
  'send-outline': Send,
  'reply': Reply,
  'reply-outline': Reply,

  // People / profile
  'person': User,
  'person-outline': User,
  'people': Users,
  'people-outline': Users,
  'person-add': CirclePlus,
  'person-add-outline': CirclePlus,
  'person-remove': CircleMinus,
  'person-remove-outline': CircleMinus,

  // Notifications / alerts
  'notifications': Bell,
  'notifications-outline': Bell,
  'notifications-off': BellOff,
  'notifications-off-outline': BellOff,
  'alert-circle': CircleAlert,
  'alert-circle-outline': CircleAlert,
  'warning': TriangleAlert,
  'warning-outline': TriangleAlert,
  'alert': TriangleAlert,
  'alert-outline': TriangleAlert,

  // Media
  'image': Image,
  'image-outline': Image,
  'images': Image,
  'images-outline': Image,
  'camera': Camera,
  'camera-outline': Camera,
  'videocam': Video,
  'videocam-outline': Video,
  'film': Video,
  'film-outline': Video,
  'mic': Mic,
  'mic-outline': Mic,
  'mic-off': MicOff,
  'mic-off-outline': MicOff,
  'musical-note': Music,
  'musical-note-outline': Music,
  'musical-notes': Music,
  'musical-notes-outline': Music,
  'volume-high': Volume2,
  'volume-high-outline': Volume2,
  'volume-medium': Volume2,
  'headset': Headphones,
  'headset-outline': Headphones,

  // Files / documents
  'document': FileText,
  'document-outline': FileText,
  'document-text': FileText,
  'document-text-outline': FileText,
  'folder': File,
  'folder-outline': File,
  'attach': Paperclip,
  'attach-outline': Paperclip,
  'archive': Archive,
  'archive-outline': Archive,

  // Playback controls
  'play': Play,
  'play-outline': Play,
  'play-circle': Play,
  'play-circle-outline': Play,
  'pause': Pause,
  'pause-outline': Pause,
  'pause-circle': Pause,
  'pause-circle-outline': Pause,
  'stop': Square,
  'stop-outline': Square,
  'stop-circle': Square,
  'stop-circle-outline': Square,
  'skip-forward': SkipForward,
  'skip-forward-outline': SkipForward,
  'skip-back': SkipForward,
  'skip-back-outline': SkipForward,

  // Actions
  'add': Plus,
  'add-outline': Plus,
  'add-circle': CirclePlus,
  'add-circle-outline': CirclePlus,
  'close': X,
  'close-outline': X,
  'close-circle': CircleX,
  'close-circle-outline': CircleX,
  'checkmark': Check,
  'checkmark-outline': Check,
  'checkmark-done': CheckCheck,
  'checkmark-done-outline': CheckCheck,
  'checkmark-circle': CircleCheck,
  'checkmark-circle-outline': CircleCheck,
  'checkmark-done-circle': CircleCheck,
  'ellipse': Circle,
  'ellipse-outline': Circle,
  'radio-button-off': Circle,
  'radio-button-on': Radio,
  'search': Search,
  'search-outline': Search,
  'pencil': Pencil,
  'pencil-outline': Pencil,
  'create': SquarePen,
  'create-outline': SquarePen,
  'trash': Trash2,
  'trash-outline': Trash2,
  'trash-bin': Trash2,
  'trash-bin-outline': Trash2,
  'share': Share2,
  'share-outline': Share2,
  'share-social': Share2,
  'share-social-outline': Share2,
  'download': Download,
  'download-outline': Download,
  'open': ExternalLink,
  'open-outline': ExternalLink,
  'copy': Copy,
  'copy-outline': Copy,
  'clipboard': Clipboard,
  'clipboard-outline': Clipboard,
  'refresh': RefreshCw,
  'refresh-outline': RefreshCw,
  'refresh-circle': RefreshCw,
  'refresh-circle-outline': RefreshCw,
  'undo': RotateCcw,
  'undo-outline': RotateCcw,

  // Security / auth
  'lock-closed': Lock,
  'lock-closed-outline': Lock,
  'lock-open': LockOpen,
  'lock-open-outline': LockOpen,
  'finger-print': ScanFace,
  'finger-print-outline': ScanFace,
  'scan': ScanFace,
  'scan-outline': ScanFace,
  'scan-circle': ScanFace,
  'scan-circle-outline': ScanFace,
  'eye': Eye,
  'eye-outline': Eye,
  'eye-off': EyeOff,
  'eye-off-outline': EyeOff,
  'shield': Shield,
  'shield-outline': Shield,
  'shield-checkmark': Shield,
  'shield-checkmark-outline': Shield,
  'key': Key,
  'key-outline': Key,
  'ban': Ban,
  'ban-outline': Ban,

  // Info / settings
  'information-circle': Info,
  'information-circle-outline': Info,
  'information': Info,
  'help': Info,
  'help-circle': Info,
  'help-circle-outline': Info,
  'settings': Settings,
  'settings-outline': Settings,
  'options': Settings,
  'options-outline': Settings,
  'log-out': LogOut,
  'log-out-outline': LogOut,

  // Misc
  'call': Phone,
  'call-outline': Phone,
  'phone-portrait': Phone,
  'at': AtSign,
  'at-outline': AtSign,
  'mail': Send,
  'mail-outline': Send,
  'location': MapPin,
  'location-outline': MapPin,
  'navigate': Navigation,
  'navigate-outline': Navigation,
  'star': Star,
  'star-outline': Star,
  'heart': Heart,
  'heart-outline': Heart,
  'thumbs-up': ThumbsUp,
  'thumbs-up-outline': ThumbsUp,
  'happy': Smile,
  'happy-outline': Smile,
  'sad': Frown,
  'sad-outline': Frown,
  'laugh': Laugh,
  'laugh-outline': Laugh,
  'time': Clock,
  'time-outline': Clock,
  'calendar': Calendar,
  'calendar-outline': Calendar,
  'home': House,
  'home-outline': House,
  'globe': Globe,
  'globe-outline': Globe,
  'link': ExternalLink,
  'link-outline': ExternalLink,
  'grid': Grid,
  'grid-outline': Grid,
  'megaphone': Megaphone,
  'megaphone-outline': Megaphone,
  'briefcase': Briefcase,
  'briefcase-outline': Briefcase,
  'bookmark': Bookmark,
  'bookmark-outline': Bookmark,
  'flag': Flag,
  'flag-outline': Flag,
  'hash': Hash,
  'tag': Tag,
  'zap': Zap,
  'zap-outline': Zap,
  'ellipsis-horizontal': Ellipsis,
  'ellipsis-horizontal-outline': Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  'ellipsis-vertical-outline': EllipsisVertical,
  'return-up-back': CornerUpLeft,
  'return-up-back-outline': CornerUpLeft,
  'cloud-upload': CloudUpload,
  'cloud-upload-outline': CloudUpload,
  'checkbox': SquareCheck,
  'checkbox-outline': SquareCheck,
};

type Props = LucideProps & { name: string };

export function Icon({ name, size = 24, color = '#000', style, ...rest }: Props) {
  const Component = MAP[name] ?? Info;
  return <Component size={size} color={color} style={style} {...rest} />;
}
